
class AppLocalizations {
  final String language;

  AppLocalizations(this.language);

  static const Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'selectLanguage': 'Select Your Language',
      'subSelectLanguage': 'Select preferred language',
      'continue': 'Continue',
      'login': 'Login',
      'loginTitle': 'Login to your account',
      'idHint': 'Enter ID or Mobile',
      'passwordHint': 'Enter Password',
      'forgotPassword': 'Forgot Password?',
      'register': 'Register',
      'newUser': 'New User?',
      'dashboard': 'Dashboard',
      'workers': 'Workers',
      'trainingModules': 'Training Modules',
      'assessments': 'Assessments',
      'certificates': 'Certificates',
      'reports': 'Reports',
      'feedback': 'Feedback',
      'settings': 'Settings',
      'welcome': 'Welcome back',
      'progress': 'Training Progress',
      'completed': 'Completed',
      'modules': 'Modules',
      'view_all': 'View All',
      'fire_title': 'Fire Safety',
      'gas_title': 'Gas Safety',
      'machinery_title': 'Machinery Safety',
      'ppe_title': 'PPE & Gear',
      'achievements': 'Achievements',
      'profile': 'Profile',
      'mine_location': 'Mine Location',
      'preferred_language': 'Preferred Language',
      'assessment': 'Assessment',
      'module_completed': 'Module Completed 🏅',
      'excellent': 'Excellent performance!',
      'correct_answers': 'Correct Answers',
      'time_taken': 'Time Taken',
      'view_cert': 'View Certificate',
      'cert_title': 'Certificate',
      'cert_heading': 'Certificate of Completion',
      'awarded_to': 'Awarded to',
      'modules_passed': 'All safety modules successfully passed.',
      'fire_guidelines_title': 'Fire Safety Guidelines & Standard Operating Procedures:',
      'fire_sop_1': 'Do not re-enter the affected area until it is declared safe by authorized personnel.',
      'fire_sop_2': 'Report missing or injured persons to the emergency response team.',
      'fire_sop_3': 'Follow site-specific emergency procedures and safety signage.',
      'fire_sop_4': 'Keep fire exits, extinguishers, alarms, and emergency equipment accessible.',
      'fire_sop_5': 'Conduct regular fire drills and emergency-response training.',
      'fire_sop_6': 'Store flammable materials safely and away from ignition sources.',
      'fire_sop_7': 'Inspect electrical equipment, gas lines, and machinery regularly.',
      'fire_sop_8': 'Maintain clear emergency communication and reporting procedures.',
      'fire_sop_9': 'Record and investigate incidents to prevent recurrence.',
      'proceed_quiz': 'Proceed to Assessment Quiz',
      'welcome_worker': 'Welcome back, Mine Worker',
      'id_prefix': 'ID: Mine Worker',
      'interactive_ar': 'Interactive AR Training',
      'simulator_title': 'Fire Extinguisher & Safety Simulator',
      'simulator_desc': 'Practice step-by-step emergency response protocols using interactive AR mode.',
      'launch_ar': 'Launch AR Simulation Now',
      'gas_title_alt': 'Gas Leakage',
      'home': 'Home',
      'awards': 'Awards',
    },
    'Hindi': {
      'selectLanguage': 'अपनी भाषा चुनें',
      'subSelectLanguage': 'अपनी पसंदीदा भाषा चुनें',
      'continue': 'आगे बढ़ें',
      'login': 'लॉग इन करें',
      'loginTitle': 'अपने खाते में लॉगिन करें',
      'idHint': 'आईडी या मोबाइल दर्ज करें',
      'passwordHint': 'पासवर्ड दर्ज करें',
      'forgotPassword': 'पासवर्ड भूल गए?',
      'register': 'पंजीकरण करें',
      'newUser': 'नया उपयोगकर्ता?',
      'dashboard': 'डैशबोर्ड',
      'workers': 'कर्मचारी',
      'trainingModules': 'प्रशिक्षण मॉड्यूल',
      'assessments': 'मूल्यांकन',
      'certificates': 'प्रमाण पत्र',
      'reports': 'रिपोर्ट',
      'feedback': 'प्रतिक्रिया',
      'settings': 'सेटिंग्स',
      'welcome': 'वापसी पर स्वागत है',
      'progress': 'प्रशिक्षण प्रगति',
      'completed': 'पूर्ण हुआ',
      'modules': 'मॉड्यूल',
      'view_all': 'सभी देखें',
      'fire_title': 'अग्निशमन सुरक्षा',
      'gas_title': 'गैस सुरक्षा',
      'machinery_title': 'मशीनरी सुरक्षा',
      'ppe_title': 'पीपीई और गियर',
      'achievements': 'उपलब्धियां',
      'profile': 'प्रोफाइल',
      'mine_location': 'खान का स्थान',
      'preferred_language': 'पसंदीदा भाषा',
      'assessment': 'मूल्यांकन',
      'module_completed': 'मॉड्यूल पूर्ण हुआ 🏅',
      'excellent': 'उत्कृष्ट प्रदर्शन!',
      'correct_answers': 'सही उत्तर',
      'time_taken': 'लिया गया समय',
      'view_cert': 'प्रमाण पत्र देखें',
      'cert_title': 'प्रमाण पत्र',
      'cert_heading': 'पूर्णता प्रमाण पत्र',
      'awarded_to': 'प्रदान किया गया',
      'modules_passed': 'सभी सुरक्षा मॉड्यूल सफलतापूर्वक उत्तीर्ण।',
      'fire_guidelines_title': 'अग्निशमन सुरक्षा दिशा-निर्देश और मानक संचालन प्रक्रियाएं:',
      'fire_sop_1': 'प्रभावित क्षेत्र में तब तक प्रवेश न करें जब तक कि अधिकृत कर्मियों द्वारा उसे सुरक्षित घोषित न किया जाए।',
      'fire_sop_2': 'लापता या घायल व्यक्तियों की सूचना आपातकालीन प्रतिक्रिया टीम को दें।',
      'fire_sop_3': 'साइट-विशिष्ट आपातकालीन प्रक्रियाओं और सुरक्षा संकेतों का पालन करें।',
      'fire_sop_4': 'अग्नि निकास, बुझाने वाले यंत्र, अलार्म और आपातकालीन उपकरण सुलभ रखें।',
      'fire_sop_5': 'नियमित रूप से फायर ड्रिल और आपातकालीन प्रतिक्रिया प्रशिक्षण आयोजित करें।',
      'fire_sop_6': 'ज्वलनशील पदार्थों को सुरक्षित रूप से और प्रज्वलन स्रोतों से दूर रखें।',
      'fire_sop_7': 'विद्युत उपकरणों, गैस लाइनों और मशीनरी का नियमित निरीक्षण करें।',
      'fire_sop_8': 'स्पष्ट आपातकालीन संचार और रिपोर्टिंग प्रक्रियाएं बनाए रखें।',
      'fire_sop_9': 'पुनरावृत्ति को रोकने के लिए घटनाओं का रिकॉर्ड रखें और जांच करें।',
      'proceed_quiz': 'मूल्यांकन क्विज़ पर आगे बढ़ें',
      'welcome_worker': 'वापसी पर स्वागत है, खदान कर्मी',
      'id_prefix': 'आईडी: खदान कर्मी',
      'interactive_ar': 'इंटरेक्टिव एआर प्रशिक्षण',
      'simulator_title': 'अग्निशामक यंत्र और सुरक्षा सिम्युलेटर',
      'simulator_desc': 'इंटरेक्टिव एआर मोड का उपयोग करके चरण-दर-चरण आपातकालीन प्रतिक्रिया प्रोटोकॉल का अभ्यास करें।',
      'launch_ar': 'एआर सिम्युलेशन अब लॉन्च करें',
      'gas_title_alt': 'गैस रिसाव',
      'home': 'होम',
      'awards': 'पुरस्कार',
    },
    'Santali': {
      'selectLanguage': 'ᱟᱢᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱚᱱ ᱢᱮ',
      'subSelectLanguage': 'Desired ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱚᱱ ᱢᱮ',
      'continue': 'ᱡᱟᱹᱨᱤ ᱫᱚᱦᱚᱭ ᱢᱮ',
      'login': 'ᱞᱚᱜᱤᱱ',
      'loginTitle': 'ᱟᱢᱟᱜ ᱮᱠᱟᱩᱱᱴ ᱨᱮ ᱞᱚᱜᱤᱱ ᱢᱮ',
      'idHint': 'ᱟᱭᱤᱰᱤ ᱵᱟᱝᱠᱷᱟᱱ ᱢᱳᱵᱟᱭᱤᱞ ᱚᱞ ᱢᱮ',
      'passwordHint': 'ᱯᱟᱥᱣᱟᱨᱰ ᱚᱞ ᱢᱮ',
      'forgotPassword': 'ᱯᱟᱥᱣᱟᱨᱰ ᱦᱤᱲᱤᱧ ᱮᱱᱟ?',
      'register': 'ᱨᱤᱡᱤᱥᱴᱟᱨ',
      'newUser': 'ᱱᱟᱣᱟ ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ?',
      'dashboard': 'ᱰᱮᱥᱵᱳᱨᱰ',
      'workers': 'ᱠᱟᱹᱢᱤᱭᱟᱹᱠᱚ',
      'trainingModules': 'ᱴᱨᱮᱱᱤᱝ ᱢᱚᱰᱭᱩᱞ',
      'assessments': 'ᱯᱚᱨᱤᱠᱷᱟ',
      'certificates': 'ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ',
      'reports': 'ᱨᱤᱯᱳᱨᱴ',
      'feedback': 'ᱯᱷᱤᱰᱵᱮᱠ',
      'settings': 'ᱥᱮᱴᱤᱝᱥ',
      'welcome': 'ᱡᱚᱦᱟᱨ',
      'progress': 'ᱴᱨᱮᱱᱤᱝ ᱜᱟᱛᱮ',
      'completed': 'ᱢᱩᱪᱟᱹᱫ ᱮᱱᱟ',
      'modules': 'ᱢᱚᱰᱭᱩᱞ ᱠᱚ',
      'view_all': 'ᱡᱚᱛᱚ ᱧᱮᱞ ᱢᱮ',
      'fire_title': 'ᱡᱩᱞᱟᱹᱣ ᱵᱚᱜᱚᱱ ᱥᱩᱨᱚᱠᱷᱭᱟ',
      'gas_title': 'ᱜᱮᱥ ᱥᱩᱨᱚᱠᱷᱭᱟ',
      'machinery_title': 'ᱢᱚᱥᱤᱱ ᱥᱩᱨᱚᱠᱷᱭᱟ',
      'ppe_title': 'ᱯᱤ.ᱯᱤ.ᱤ ᱡᱤᱱᱤᱥ',
      'achievements': 'ᱦᱟᱢᱮᱴ ᱠᱚ',
      'profile': 'ᱯᱨᱳᱯᱷᱟᱭᱤᱞ',
      'mine_location': 'ᱠᱷᱟᱫᱟᱱ ᱴᱷᱟᱶ',
      'preferred_language': 'ᱠᱩᱥᱤ ᱯᱟᱹᱨᱥᱤ',
      'assessment': 'ᱯᱚᱨᱤᱠᱷᱟ',
      'module_completed': 'ᱢᱚᱰᱭᱩᱞ ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ 🏅',
      'excellent': 'ᱱᱟᱯᱟᱭ ᱠᱟᱹᱢᱤ!',
      'correct_answers': 'ᱠᱚᱲᱟ ᱨᱩᱣᱟᱹᱲ',
      'time_taken': 'အချိန် ᱦᱟᱛᱟᱣ ᱮᱱᱟ',
      'view_cert': 'ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱧᱮᱞ ᱢᱮ',
      'cert_title': 'ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ',
      'cert_heading': 'ᱯᱩᱨᱟᱹᱣ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ',
      'awarded_to': 'Sharing ᱮᱱᱟ',
      'modules_passed': 'ᱡᱚᱛᱚ ᱥᱩᱨᱚᱠᱷᱭᱟ ᱢᱚᱰᱭᱩᱞ ᱯᱟᱨᱚᱢ ᱮᱱᱟ᱾',
      'fire_guidelines_title': 'ᱡᱩᱞᱟᱹᱣ ᱵᱚᱜᱚᱱ ᱥᱩᱨᱚᱠᱷᱭᱟ ᱟᱱᱟᱜ ᱰᱟᱦᱟᱨ ᱟᱨ ᱠᱟᱹᱢᱤ ᱦᱚᱨᱟ:',
      'fire_sop_1': 'ᱚᱠᱚᱭ ᱦᱚᱲ ᱦᱚᱸ ᱵᱟᱠᱚ ᱵᱚᱞᱚᱣᱟ ᱡᱩᱫᱤ ᱚᱸᱰᱮ ᱥᱩᱨᱚᱠᱷᱭᱟ ᱵᱟᱝ ᱠᱚ ᱞᱟᱹᱭᱟ᱾',
      'fire_sop_2': 'ᱦᱟᱹᱱᱤ ᱟᱠᱟᱱ ᱵᱟᱝᱠᱷᱟᱱ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱨᱮ ᱢᱮᱱᱟᱜ ᱠᱚ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱭ ᱠᱚ ᱢᱮ᱾',
      'fire_sop_3': 'ᱥᱟᱱᱟᱢ ᱥᱩᱨᱚᱠᱷᱭᱟ ᱪᱤᱱᱦᱟᱹ ᱠᱚ ᱢᱟᱱᱟᱣ ᱵᱟᱛᱟᱣ ᱢᱮ᱾',
      'fire_sop_4': 'ᱚᱜᱽᱱᱤ ᱱᱤᱠᱟᱥ, ᱥᱤᱵᱤᱞ ᱡᱤᱱᱤᱥ ᱠᱚ ᱥᱟᱯᱲᱟᱣ ᱫᱚᱦᱚᱭ ᱢᱮ᱾',
      'fire_sop_5': 'ᱫᱤᱱᱟᱹᱢ ᱦᱤᱞᱚᱜ ᱯᱷᱟᱭᱟᱨ ᱰᱨᱤᱞ ᱠᱚ ᱥᱟᱯᱲᱟᱣ ᱢᱮ᱾',
      'fire_sop_6': 'ᱡᱩᱞᱟᱹᱣ ᱡᱤᱱᱤᱥ ᱠᱚ ᱥᱟᱺᱜᱤᱧ ᱨᱮ ᱫᱚᱦᱚᱭ ᱢᱮ᱾',
      'fire_sop_7': 'ᱤᱞᱮᱠᱴᱨᱤᱠ ᱥᱟᱯᱷᱟ ᱟᱨ ᱢᱚᱥᱤᱱ ᱠᱚ ᱧᱮᱞ ᱡᱚᱛᱚᱱ ᱢᱮ᱾',
      'fire_sop_8': 'ᱡᱚᱛᱚ ᱠᱷᱚᱱ ᱱᱟᱯᱟᱭ ᱥᱩᱨᱚᱠᱷᱭᱟ ᱥᱟᱹᱜᱟᱹᱭ ᱫᱚᱦᱚᱭ ᱢᱮ᱾',
      'fire_sop_9': 'ਘಟನೆ ᱠᱚ ᱵᱟᱝ ᱦᱩᱭ ᱚᱪᱚ ᱞᱟᱹᱜᱤᱫ ᱧᱮᱞ ᱡᱚᱛᱚᱱ ᱢᱮ᱾',
      'proceed_quiz': 'ᱯᱚᱨᱤᱠᱷᱟ ᱠᱤᱭᱩᱡᱽ ᱛᱮ ᱞᱟᱦᱟᱜ ᱢᱮ',
      'welcome_worker': 'ᱡᱚᱦᱟᱨ, ᱠᱷᱟᱫᱟᱱ ᱠᱟᱹᱢᱤᱭᱟᱹ',
      'id_prefix': 'ᱟᱭᱤᱰᱤ: ᱠᱷᱟᱫᱟᱱ ᱠᱟᱹᱢᱤᱭᱟᱹ',
      'interactive_ar': 'ᱡᱚᱱᱚᱲᱟᱣ ᱮ.ᱟᱨ. ᱴᱨᱮᱱᱤᱝ',
      'simulator_title': 'ᱟᱜ ᱚᱨᱚᱜ ᱟᱨ ᱥᱩᱨᱚᱠᱷᱭᱟ ᱥᱤᱢᱩᱞᱮᱴᱚᱨ',
      'simulator_desc': 'ᱡᱚᱱᱚᱲᱟᱣ ᱮ.ᱟᱨ. ᱢᱳᱰ ᱵᱮᱵᱷᱟᱨ ᱠᱟᱛᱮ ᱟᱯᱟᱛᱠᱟᱞᱤᱱ ᱨᱩᱣᱟᱹᱲ ᱦᱚᱨᱟ ᱠᱚ ᱟᱵᱷᱭᱟᱥ ᱢᱮ᱾',
      'launch_ar': 'ᱮ.ᱟᱨ. ᱥᱤᱢᱩᱞᱮᱥᱚᱱ ᱮᱦᱚᱵ ᱢᱮ',
      'gas_title_alt': 'ᱜᱮᱥ ᱞᱤᱠᱮᱡ',
      'home': 'ᱚᱲᱟᱜ',
      'awards': 'ᱥᱤᱨᱯᱷᱟᱹ',
    },
  };

  static String get(String language, String key) {
    final langMap = _localizedValues[language] ?? _localizedValues['English']!;
    return langMap[key] ?? _localizedValues['English']![key] ?? key;
  }

  String translate(String key) {
    return AppLocalizations.get(language, key);
  }
}